apiVersion: v1
kind: Service
metadata:
 labels:
  app: api-service
 name: api-service
 namespace: platform
spec:
 ports:
 - name: '1234'
   port: 1234
   protocol: TCP
   targetPort: 1234
 selector:
  app: flows-operator
   sessionAffinity: None
   type: ClusterIP