kind: Deployment
apiVersion: apps/v1
metadata:
 name: communication-router
 namespace: platform
 labels:
  app: communication-router
spec:
 replicas: 1
 selector:
  matchLabels:
   app: communication-router
 template:
  metadata:
   name: communication-router
   labels:
    app: communication-router
  spec:
   containers:
   - name: communication-router
     image: openintegrationhub/communication-router:latest
     env:
     - name: RABBITMQ_URI
       value: amqp://guest:guest@rabbitmq-service.platform.svc.cluster.local
     - name: LISTEN_PORT
       value: '1234'
     - name: LOG_LEVEL
       value: trace
     terminationMessagePath: "/dev/termination-log"
     terminationMessagePolicy: File
     imagePullPolicy: Always
     livenessProbe:
      httpGet:
       path: "/healthcheck"
       port: 1234
     readinessProbe:
      httpGet:
       path: "/healthcheck"
       port: 1234
     securityContext:
      privileged: false
   serviceAccountName: flows-operator-account
   restartPolicy: Always
   terminationGracePeriodSeconds: 30
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 1
    maxSurge: 1