apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
 name: flows.elastic.io
 namespace: flows
spec:
 group: elastic.io
 names:
  kind: Flow
  listKind: FlowList
  plural: flows
  shortNames: []
  singular: flow
 scope: Namespaced
 version: v1