apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: flows-operator-clusterrole
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch