kind: Deployment
apiVersion: apps/v1
metadata:
 name: rabbitmq
 namespace: platform
labels:
 app: rabbitmq
spec:
 replicas: 1
 selector:
  matchLabels:
   app: rabbitmq
 template:
  metadata:
   name: rabbitmq
   labels:
    app: rabbitmq
  spec:
   containers:
   - name: rabbitmq
     image: rabbitmq:management
   envFrom: []
   terminationMessagePath: "/dev/termination-log"
   terminationMessagePolicy: File
   imagePullPolicy: Always
   securityContext:
    privileged: false
   livenessProbe:
    tcpSocket:
     port: 5672
 restartPolicy: Always
 terminationGracePeriodSeconds: 30
strategy:
 type: RollingUpdate
 rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1