kind: Deployment
apiVersion: apps/v1
metadata:
 name: scheduler
 namespace: platform
 labels:
  app: scheduler
spec:
 replicas: 1
 selector:
  matchLabels:
   app: scheduler
 template:
  metadata:
   name: scheduler
   labels:
    app: scheduler
  spec:
   containers:
   - name: scheduler
     image: openintegrationhub/scheduler:latest
     env:
     - name: RABBITMQ_URI
       value: amqp://guest:guest@rabbitmq-service.platform.svc.cluster.local
     - name: LISTEN_PORT
       value: '1234'
     terminationMessagePath: "/dev/termination-log"
     terminationMessagePolicy: File
     imagePullPolicy: Always
     livenessProbe:
      httpGet:
       path: "/healthcheck"
       port: 1234
     readinessProbe:
      httpGet:
       path: "/healthcheck"
       port: 1234
     securityContext:
      privileged: false
  serviceAccountName: flows-operator-account
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 1
   maxSurge: 1